/* Generated by scripts/generate_cffi_exports.py from CDEF in
 * pstrain/lib/_cffi/cdef.py. Do not edit; run `make cffi-exports-gen`.
 * See the handshake comment in pstrain_align.h. */
#ifndef PSTRAIN_INTERFACE_FINGERPRINT_H
#define PSTRAIN_INTERFACE_FINGERPRINT_H
#define PSTRAIN_INTERFACE_FINGERPRINT "5bfd5b3a8031c91c0bbd3044c6bf3df60a58736b942982e407874207c6a22046"
#endif
