#!/usr/bin/env python3
"""Generate platform linker export lists and the interface fingerprint header.

Both derive from the CFFI declarations (``CDEF``); ``--check`` verifies that the
checked-in copies match, so an edit to ``CDEF`` fails ``make config-check``
until ``make cffi-exports-gen`` is rerun.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cffi import FFI

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pstrain.lib._cffi.cdef import CDEF  # noqa: E402
from pstrain.lib._cffi.core import interface_fingerprint  # noqa: E402

FINGERPRINT_HEADER = ROOT / "csrc" / "libs" / "libpstrain" / "pstrain_interface_fingerprint.h"


def cffi_functions() -> list[str]:
    """Return the complete function surface declared to ABI-mode CFFI."""
    ffi = FFI()
    ffi.cdef(CDEF)
    return sorted(
        key.removeprefix("function ")
        for key in ffi._parser._declarations  # type: ignore[attr-defined]
        if key.startswith("function ")
    )


def rendered_fingerprint_header() -> str:
    """Render the C header carrying the fingerprint of ``CDEF``."""
    return (
        "/* Generated by scripts/generate_cffi_exports.py from CDEF in\n"
        " * pstrain/lib/_cffi/cdef.py. Do not edit; run `make cffi-exports-gen`.\n"
        " * See the handshake comment in pstrain_align.h. */\n"
        "#ifndef PSTRAIN_INTERFACE_FINGERPRINT_H\n"
        "#define PSTRAIN_INTERFACE_FINGERPRINT_H\n"
        f'#define PSTRAIN_INTERFACE_FINGERPRINT "{interface_fingerprint(CDEF)}"\n'
        "#endif\n"
    )


def rendered_exports() -> dict[Path, str]:
    """Render the export allowlists and the fingerprint header from ``CDEF``."""
    names = cffi_functions()
    elf = "{\n  global:\n" + "".join(f"    {name};\n" for name in names)
    elf += "  local:\n    *;\n};\n"
    macos = "".join(f"_{name}\n" for name in names)
    windows = "LIBRARY pstrainc\nEXPORTS\n" + "".join(f"    {name}\n" for name in names)
    return {
        ROOT / "csrc" / "pstrain.exports.elf": elf,
        ROOT / "csrc" / "pstrain.exports.macos": macos,
        ROOT / "csrc" / "pstrain.exports.def": windows,
        FINGERPRINT_HEADER: rendered_fingerprint_header(),
    }


def main() -> int:
    """Write export lists, or verify checked-in lists with ``--check``."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mismatches = []
    for path, expected in rendered_exports().items():
        if args.check:
            if not path.is_file() or path.read_text() != expected:
                mismatches.append(path.relative_to(ROOT))
        else:
            path.write_text(expected)
    if mismatches:
        print(
            "stale CFFI generated files (run `make cffi-exports-gen`): "
            + ", ".join(map(str, mismatches)),
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
